# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, "10.11"

# ignore all warnings from all pods
inhibit_all_warnings!

target "NER" do
  
  #Amazon
  pod 'Bolts'
  
  #Networking
  pod 'AFNetworking', '= 2.3.1'
  
  #Utilities
  pod 'ReactiveCocoa', '= 2.1.8'
  pod 'UICKeyChainStore', '= 2.1.0'
  pod 'libextobjc', '= 0.4.1'
  pod 'SSZipArchive', '= 1.1'
  
  pod 'Ashton', '= 1.0.0'
  
end
